goxiaoy/flutter_survey_js

lib/model/survey.dart, lib/model/survey.g.dart, test/survey_test.dart
=> Made it so that Survey data object can parse boolean showQuestionNumbers values

lib/model/element.dart, test/model/element_test.dart
=> Made it so that framework does fail gracefully when attempting to parse unsupported element types

lib/ui/elements/text.dart, test/questions/text_test.dart
This makes it so that all tests are passing on main.
=> Removed obsolete tests - DC

lib/ui/elements/rating.dart, lib/ui/elements/survey_element_factory.dart, lib/ui/elements/text.dart, lib/ui/form_control.dart, lib/ui/survey_widget.dart, test/questions/rating_test.dart, test/questions/text_test.dart
This would resolve Issue #22.
This PR also makes a `Rating`'s `defaultValue` be reflected when building said `ReactiveSegmentedControl`.
I removed `lib/ui/survey_widget.dart` line 118: `formGroup.value = widget.answer;` because this line was overwriting the `defaultValue` we parse out of the JSON. I'm not sure if this removes important functionality and/or there is a way to reconcile this.
=> Made it so that `ratingBuilder`'s `ReactiveSegmentedControl`'s selected segment has white text.

lib/ui/survey_widget.dart, test/ui/survey_widget_test.dart
=> Made it so that `SurveyWidget` only uses a `PageView` if it has more than one page - DC

lib/ui/survey_widget.dart
=> Made it so that you can pass custom padding to `SurveyWidget` - DC

lib/model/survey.dart, lib/model/survey.g.dart, lib/ui/elements/multiple_text.dart, lib/ui/elements/survey_element_factory.dart, test/questions/dropdown_test.dart, test/questions/multiple_text_test.dart
=> Fixed Issue #43: Add `placeholder` support to `Dropdown` and `Multiple Text`

lib/ui/elements/multiple_text.dart, lib/ui/elements/question_title.dart, lib/ui/elements/survey_element_factory.dart, lib/ui/reactive/reactive_group_button.dart
This PR:
- Makes `Comment` multi-line
- Minimizes leading spacing on radio buttons
- Increases the spacing between `Multiple Text` title and its children
- Increases the spacing between `Comment`'s title widget and and its `ReactiveTextField`
=> General UI improvements

example/assets/complex.json, lib/ui/elements/survey_element_factory.dart, test/questions/boolean_test.dart
=> Added labelFalse and labelTrue support for Boolean element

lib/generated/intl/messages_all.dart, lib/generated/intl/messages_en.dart, lib/generated/intl/messages_zh.dart, lib/generated/l10n.dart, lib/l10n/intl_en.arb, lib/l10n/intl_zh.arb, lib/ui/elements/survey_element_factory.dart, pubspec.lock, pubspec.yaml, test/questions/dropdown_test.dart
=> Fixed Issue #46: `Dropdown`s without a specified `placeholder` should default to `"Submit..."` or `"请选择..."`

lib/ui/survey_widget.dart
=> Provide means to react on validation errors

lib/ui/elements/dropdown.dart, test/questions/dropdown_test.dart
Resolves #59
https://user-images.githubusercontent.com/27797194/236502464-f640d0fa-8454-4ede-87b0-09ce9ea09bab.mov
=> Fixed Issue #59: Required Dropdown with showOtherItem true validates prematurely

example/assets/complex.json, lib/generated/intl/messages_en.dart, lib/generated/intl/messages_zh.dart, lib/generated/l10n.dart, lib/l10n/intl_en.arb, lib/l10n/intl_zh.arb, lib/ui/elements/checkbox.dart, pubspec.lock
=> Checkbox to support `showSelectAllItem`, `showNoneItem` and `showOtherItem`

lib/ui/elements/checkbox.dart, test/questions/check_boxes_test.dart
=> Checkbox bugfix 63

.run/Run Tests.run.xml, .run/tests in _schema_flutter_survey_js_model_test.run.xml, README.md, example/pubspec.lock, pubspec.lock, schema/flutter_survey_js_model/test/survey_test.dart
Our team went ahead and added back some tests that were removed from survey_test.dart with the recent refactor of how we serialize objects.
=> Resurrected some survey_test tests - DC

lib/ui/elements/checkbox.dart, lib/ui/form_control.dart, test/questions/check_boxes_test.dart
=> Checkbox untouched

lib/ui/elements/text.dart, lib/ui/reactive/reactive.dart, test/questions/text_test.dart
=> number input to allow both ints and doubles

lib/ui/elements/text.dart
This implements text input for `time`.
=> Text input for time

CHANGELOG.md, example/pubspec.yaml, lib/ui/validators.dart, pubspec.yaml, schema/flutter_survey_js_model/CHANGELOG.md, schema/flutter_survey_js_model/pubspec.yaml, test/questions/multiple_text_test.dart
This would close #109 and create a new release.
Let me know if there is anything you do not like around versioning/CHANGELOG.md changes. @goxiaoy
=> Added required validation to MultipleText and publish packages.

packages/flutter_survey_js/lib/ui/elements/question_title.dart
This would resolve Issue #118.
=> Fixed question number misalignment - DC

packages/flutter_survey_js/lib/ui/elements/checkbox.dart, packages/flutter_survey_js/test/questions/check_boxes_test.dart
=> Added fix for CheckboxListTiles not initially being checked when Checkbox other value is provided and SurveyWidget is built using a builder
